#!/bin/sh
model=mtlinadapt
fold=1
for perc in 20
    do nohup ./run -multi true -fv 10 -model $model -fold $fold -perc $perc -saveModel true -savePerf true -global ./data/new_global_$fold.txt > ./log/Model_$model\_fold_$fold\_perc_$perc.log
done


#for fold in 1 2 3 4 5
#    do for perc in 10 20 30 40 50 60 70 80 90
#            do nohup ./run -fv 10 -model $model -fold $fold -perc $perc -saveModel true -savePerf true -global ./data/new_global_$fold.txt > ./log/Model_$model\_fold_$fold\_perc_$perc.log
#        done
#    done
